### PR TITLE
If switch on for multiple file add the sort column to the database

### PR DESCRIPTION
**Pull request by baumannsven**
The file attribute use permanently the virtual sort attribute. We must have the virtual sort attribute only the file attribute works in the multiple mode.

### CODE REVIEW

**Comment by zonky2** [comment]
@baumannsven: have you a reference item?

**Comment by baumannsven** [comment]
@zonky2 What do you mean with reference item?

This can be tested. 

Please test update handler (runonce) too. For the update handler test you must delete the columns ending with _sort in all mm_* tables.

**Comment by zonky2** [comment]
@baumannsven sorry - I mean Issue ...

**Comment by baumannsven** [comment]
No exist in issue for this

**Comment by zonky2** [comment]
> or add description

**Comment by baumannsven** [comment]
If merge this pull request you must use https://github.com/MetaModels/core/pull/1107 to.

**Comment by zonky2** [comment]
note: think about an exception if column `*_sort` already exist...

**Comment by baumannsven** [comment]
For works correctly by sort manual, must be merge this https://github.com/MetaModels/attribute_translatedfile/pull/14

**Pull request merged**
